### ISSUE TITLE
feature extraction 관련 질문입니다.

### ISSUE THREAD

**Issue by isangu** [ai4r/AIR-deep-turn#1]
현재 고령자 멀티모달 데이터셋 중 일부를 다운받아 해당 Repository를 사용해보려 합니다.

turn-taking-dataset의 conversation_audio 폴더의 .wav 파일들을 이용해

feature_extraction.py 로 feature file들을 생성하고, train.py 를 이용해 해당 feature file들의 path와 annotation path를 주어

학습을 진행하는 것으로 이해했습니다.

feature_extraction.py로 conversation_audio의 .wav 파일들을 처리 시 다음과 같이 mfcc와 onset_feat의 shape이 달라 concatenate가

이루어지지 않는 것 같습니다. 혹시 다른 .wav파일을 이용하거나 preprocessing 과정을 거쳐야 하는 건가요?

![Screenshot from 2020-08-12 17-56-19](https://user-images.githubusercontent.com/24788424/89995976-312e3000-dcc5-11ea-9fc7-795ebc40a0f1.png)

**Comment by bettlekor** [comment]
예, 전처리 과정을 거쳐야합니다.
