### ISSUE TITLE
eval_model.py 관련 질문입니다.

### ISSUE THREAD

**Issue by isangu** [ai4r/AIR-deep-turn#2]
Repository 사용 도중 의문이 있어 질문 드립니다.

1. Annotation .csv 파일의 숫자가 어떤 행동을 의미하는지 알 수 있나요?

2. 
![Screenshot from 2020-08-21 13-09-25](https://user-images.githubusercontent.com/24788424/90851438-b6919e80-e3af-11ea-88b7-3b2fdcc346f8.png)
![Screenshot from 2020-08-21 13-09-37](https://user-images.githubusercontent.com/24788424/90851442-b7c2cb80-e3af-11ea-924d-bd959ff5d7aa.png)  
evaluation 진행 시 다음과 같이 코드를 작성해 출력하니 label이 0~6까지 출력을 하는 것 같습니다.
그리고 target값이 0,1,2,3,5로 중간에 4가 없는 것 같은데 맞는 것인지 궁금합니다.

**Comment by bettlekor** [comment]
1. turn-taking 4종과 상대편이 말하는 상태를 의미합니다.
 - take: 0, release: 1, wait: 2, hold:3, other_speech:5
2. label에 4는 없습니다.
 - prediction 결과는 확인해 보겠습니다.
